spring:
  datasource:
    url: jdbc:postgresql://dzoms_user_service_postgres:5433/user_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog.xml
  web:
    resources:
      add-mappings: false
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
